from tkinter import *
from PIL import ImageTk, Image
ventana = Tk()
ventana.title('Botones')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\icon.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\netflix.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\Spotify.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\Amazon.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\HBO.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\USB.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\Camara.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\musica.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\video.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\video2.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\play.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\pausa.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\next.png')
ventana.iconbitmap(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\previous.png')

imagen= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\icon.png').resize((100, 100)))
imagen2= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\netflix.png').resize((80, 80)))
imagen3= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\Spotify.png').resize((80, 80)))
imagen4= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\Amazon.png').resize((100, 100)))
imagen5= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\HBO.png').resize((80, 80)))
imagen6= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\USB.png').resize((90, 90)))
imagen7= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\Camara.png').resize((90, 90)))
imagen8= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\musica.png').resize((90, 90)))
imagen9= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\video.png').resize((90, 90)))
imagen10= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\video2.png').resize((90, 90)))
imagen11= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\play.png').resize((80, 80)))
imagen12= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\pausa.png').resize((80, 80)))
imagen13= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\next.png').resize((80, 80)))
imagen14= ImageTk.PhotoImage(Image.open(r'D:\Facultad\SistemasEmbebidos\SmartHome\Botones\previous.png').resize((80, 80)))

boton1 = Button(image = imagen, width= 80, height=80,relief="flat").place(x=0,y=10)
boton2 = Button(image = imagen2,width= 80, height=80,relief="flat" ).place(x=0,y=150)
boton3 = Button(image = imagen3,width= 80, height=85,relief="flat" ).place(x=0,y=310)
boton4 = Button(image = imagen4,width= 80, height=80,relief="flat" ).place(x=150,y=10)
boton5 = Button(image = imagen5,width= 75, height=75,relief="flat" ).place(x=150,y=145)
boton6 = Button(image = imagen6,width= 75, height=75,relief="flat" ).place(x=150,y=310)
boton7 = Button(image = imagen7,width= 90, height=75,relief="flat" ).place(x=280,y=20)
boton8 = Button(image = imagen8,width= 90, height=75,relief="flat" ).place(x=280,y=145)
boton9 = Button(image = imagen9,width= 90, height=75,relief="flat" ).place(x=280,y=310)
boton10 = Button(image = imagen10,width= 90, height=75,relief="flat" ).place(x=420,y=10)
boton11 = Button(image = imagen11,width= 90, height=80,relief="flat" ).place(x=420,y=145)
boton12 = Button(image = imagen12,width= 90, height=80,relief="flat" ).place(x=420,y=310)
boton13 = Button(image = imagen13,width= 90, height=80,relief="flat" ).place(x=610,y=10)
boton14 = Button(image = imagen14,width= 90, height=80,relief="flat" ).place(x=610,y=145)


ventana.mainloop()